<a href="https://colab.research.google.com/github/egag8843/Colab_New/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/07/05
이름 : 장경준
내용 : 파이썬 Numpy 패키지 실습하기
"""
import numpy  as  np


In [ ]:
# Numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
print('v1 = ',v1)

v2 = np.arange(5)
print('v2 = ', v2)

v3 = np.arange(10)
print('v3 = ',v3)

v1 =  [1 2 3 4 5]
v2 =  [0 1 2 3 4]
v3 =  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0~1 사이의 임의의ㅡ 실수
rand1 = np.random.rand(100)
print(rand1)
# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)
# 0~9 사이의 임의의 정수
rand3 = np.random.randint(10)
print(rand3)

In [ ]:
#Numpy 자료구조 - 행렬
m1 = np.array([[1,2],[3,4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)

In [ ]:
# 전치행렬
print(m1.T)

print(m2.transpose())

In [ ]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

In [ ]:
#역행렬
im1 = np.linalg.inv(m1)
print(im1)


In [ ]:
#행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)

print(matrix[0,0])
print(matrix[0,:])
print(matrix[:,0])

print(matrix[0:2,0:2])
print(matrix[:,0:2])
print(matrix[:,2:4])
print(matrix[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
